export const baseRoute ="http://127.0.0.1:8000/"
export  const homeRoute =baseRoute+"home/"
export const testRoute=baseRoute+"test/"
export const addTestRoute = baseRoute+"add/"
export const loginRoute =baseRoute+"login/"
export const registerRoute = baseRoute+"register/"